### ISSUE TITLE
Permission Denied for Realsense-ros Jetson NX

### ISSUE THREAD

**Issue by krishnaadithya** [AndreV84/jetson-containers#1]
$xhost +
xhost:  unable to open display ""

$docker run -it --rm --net=host --runtime nvidia -e DISPLAY=$DISPLAY --privileged --ipc=host -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v /tmp/argus_socket:/tmp/argus_socket --cap-add SYS_PTRACE realsense_cuda:latest /bin/bash -c '. devel/setup.bash; roslaunch realsense2_camera rs_camera.launch'

docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by AndreV84** [comment]
Hi @krishnaadithya 
you would either need to  add the user to docker group [ recommended]
```
 sudo usermod -aG docker $USER
```
or use sudo with docker [ not recommended]

**Comment by AndreV84** [comment]
let me know if you have any other issues, otherwise the issue is considered resolved
